// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using PartialFoods.Services.OrderManagementServer.Entities;

namespace PartialFoods.Services.OrderManagementServer.Migrations
{
    [DbContext(typeof(OrdersContext))]
    [Migration("20171015152123_AddActivities")]
    partial class AddActivities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.LineItem", b =>
                {
                    b.Property<string>("OrderId");

                    b.Property<string>("SKU");

                    b.Property<int>("Quantity");

                    b.Property<int>("UnitPrice");

                    b.HasKey("OrderId", "SKU");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreatedOn");

                    b.Property<int>("TaxRate");

                    b.Property<string>("UserId");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.OrderActivity", b =>
                {
                    b.Property<string>("OrderId");

                    b.Property<string>("ActivityId");

                    b.Property<int>("Activity");

                    b.Property<long>("OccuredOn");

                    b.Property<string>("UserId");

                    b.HasKey("OrderId", "ActivityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.LineItem", b =>
                {
                    b.HasOne("PartialFoods.Services.OrderManagementServer.Entities.Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.OrderActivity", b =>
                {
                    b.HasOne("PartialFoods.Services.OrderManagementServer.Entities.Order")
                        .WithMany("Activities")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
